### ISSUE TITLE
Need dynamic number of membrane sides

### ISSUE THREAD

**Issue by erights** [ajvincent/es7-membrane#59]
By naming your membrane sides with strings, you make it awkward to accommodate a dynamic number of membrane sides that vary with runtime conditions. A motivating case would be Horton

https://research.google.com/pubs/pub33037.html
http://www.erights.org/elib/capability/horton/

By using symbols instead of strings, this conflict should go away naturally.

**Comment by ajvincent** [comment]
ProxyMapping.prototype.setLocalFlag and .getLocalFlag need to be redesigned for symbols.
