### ISSUE TITLE
Membrane.modifyRules.truncateArgList(true / false / number) for apply/construct traps

### ISSUE THREAD

**Issue by ajvincent** [ajvincent/es7-membrane#86]
Performance and memory consumption could potentially be hurt by a malicious actor passing in thousands of objects to a function that doesn't care about extra arguments... particularly for a membrane that has to wrap each argument in a function call.  During the lifetime of that call, at least, these arguments stay in memory.  If a function takes zero arguments, that's a huge waste and could add unnecessary pressure to memory, or to garbage collection.

The membrane could have a modifyRulesAPI method to protect against this form of poisoning.

true:  Limit the argument count to the target function's arity.
false:  No restriction on the number of arguments.
number:  Limit the argument count to the given number.

**Comment by ajvincent** [comment]
In particular, getters should be restricted to zero arguments and setters to one argument.

**Comment by davidturissini** [comment]
@ajvincent how do you propose to detect a function's arity? toString?

**Comment by davidturissini** [comment]
I'll take a stab at this

**Comment by ajvincent** [comment]
@davidturissini Before you dive too deep into the getter/setter limiting I mentioned above, see #88.

**Comment by ajvincent** [comment]
Fixed with commit 50ed10d
