### ISSUE TITLE
Optimization:  Get/set methods in descriptors probably don't need full proxy wrapping

### ISSUE THREAD

**Issue by ajvincent** [ajvincent/es7-membrane#88]
Who looks up the properties of a .get() function of an accessor descriptor?  A simple function to interact with the ObjectGraphHandler should be more than sufficient for the majority case, instead of a proxy.

Membrane.prototype.wrapDescriptor should be where we fix this.

Ditto for setters.

If someone disagrees (and believes in defining properties on getter functions), we can make full-wrapping of the get/set functions an option in the modifyRulesAPI... but I do believe that would be dumb.

**Comment by ajvincent** [comment]
However, the getter and setter functions must respect revocation of the "this" object proxy.

**Comment by davidturissini** [comment]
I'm not sure I'm 100% clear on this. Are you suggesting that we never wrap getter and setter methods in a proxy, and just wrap in a custom function instead?

**Comment by ajvincent** [comment]
Yes.

**Comment by ajvincent** [comment]
This will be backed out for #6, #162.  It turns out manually creating the desc.set and desc.get properties of the descriptor as unique functions every time breaks the tests when the Membrane constructor is itself wrapped in a membrane.
